version: "3"
services: 
    ws-server:
        build: server/
        command: node index.js
        container_name: ws-server
        ports: 
            - "8080:8080"
        links: 
            - mongodb
        depends_on: 
            - mongodb
    client:
        build: client/
        container_name: ws-client
        command: node index.js
        network_mode: host
        depends_on: 
            - ws-server
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
